### PR TITLE
For MEB, add 3 more datasets and function lookups

### PR DESCRIPTION
**Pull request by AlexEdgcomb**
Fixes https://zybooks.atlassian.net/browse/ZTOOL-218

### CODE REVIEW

**Comment by AlexEdgcomb** [comment]
@ArianJM , ready for review

**Comment by AlexEdgcomb** [comment]
@ArianJM , fyi, the author requested a tweak to the parameters. I made the tweak

**Comment by ArianJM** [comment]
@AlexEdgcomb ready to merge.

**Comment by AlexEdgcomb** [comment]
Please merge :)

**Pull request merged**
