### PR TITLE
Add Zyante Linear algebra module ztool 97

### PR DESCRIPTION
**Pull request by ArianJM**
Partially fixes: https://zybooks.atlassian.net/browse/ZTOOL-97

Adds a `zyante` module that contains a `linearalgebra` module with these functions: 
```
makeRandomMatrix
dot_product
latexMatrix
create_identity_matrix
create_swap_elementary_matrix
create_scale_elementary_matrix
create_add_elementary_matrix
multiply_matrix
generate_equations_from_matrix
```

The implementation of those functions comes from: https://github.com/zyBooks/zyTools/blob/master/tools/ProgressionUtilities/js/utilities.js#L8

Now doing something like: 
```
from zyante import linearalgebra

print linearalgebra.makeRandomMatrix(2, 2)
```
Would print a 2x2 random matrix.

Note, there are 7 files changed... I only changed the last two (in `src/lib/zyante`). I don't know why it thinks the other files changed...

### CODE REVIEW

**Comment by ArianJM** [comment]
@AlexEdgcomb ready.

**Comment by AlexEdgcomb** [comment]
@ArianJM , functionally, would be preferably to be able to do something like:
```
from linear_algebra import *

print makeRandomMatrix(2, 2) # No prefix needed!
```

Maybe the import has to be something like this: `from zyante.linear_algebra import *`, but it'd be nice to not have to prefix every function with the module name.

Also, I think python modules use underscore notation, like: `linear_algebra`:
https://www.python.org/dev/peps/pep-0008/#package-and-module-names

> Note, there are 7 files changed... I only changed the last two (in src/lib/zyante). I don't know why it thinks the other files changed...

Can you revert the other files, so they aren't in the PR? One idea is to start a new branch and copy in your changes.

**Comment by ArianJM** [comment]
@AlexEdgcomb I can remove the `zyante` package name, It's not needed at all, but I thought maybe we can have everything under that name.

Right now we can have `from zyante.linearalgebra import generate_equations_from_matrix` (I don't know why `*` doesn't work). Anyway, it's good practice to be specific and not just import `*`, though maybe that's more for external modules.

I'll take a look tomorrow.

**Comment by ArianJM** [comment]
@AlexEdgcomb done. This will work now:
```
from linear_algebra import *

print makeRandomMatrix(2, 2) # No prefix needed!
```

**Pull request merged**
