### PR TITLE
Improve load speed of meb module

### PR DESCRIPTION
**Pull request by AlexEdgcomb**
Part of https://zybooks.atlassian.net/browse/ZTOOL-218

Reduces module load time from 1.1 to 0.7 seconds.

I found that delayed load of datasets did not improve load time.

### CODE REVIEW

**Comment by AlexEdgcomb** [comment]
@ArianJM , ready for review

**Comment by ArianJM** [comment]
@AlexEdgcomb looks good.

**Comment by AlexEdgcomb** [comment]
@ArianJM , ready to merge :)

**Comment by AlexEdgcomb** [comment]
@ArianJM , ready to merge :)

**Comment by AlexEdgcomb** [comment]
@ArianJM , ready to merge :)

**Pull request merged**
